---
- name: Create Docker folders
  file:
    path: "{{ root_directory }}"
    owner: root
    group: docker
    state: directory
    mode: 0755
- name: Copy compose file
  template:
    src: ./files/docker-compose.prod.yml.j2
    dest: "{{ root_directory }}/docker-compose.yml"
  become: yes
- name: Copy configs
  copy:
    src: ./files/config/
    dest: "{{ config_directory }}"
  become: yes
- name: Login to Github Registries
  docker_login:
    registry: "{{ docker.registry }}"
    username: "{{ docker.username }}"
    password: "{{ docker.password }}"
- name: Pull latest images
  command: docker-compose --log-level error -f "{{ root_directory }}/docker-compose.yml" pull
- name: Up
  command: docker-compose --log-level error -f "{{ root_directory }}/docker-compose.yml" up -d
# - name: Deploy services
#   command: docker --log-level ERROR stack deploy -c "{{ root_directory }}/docker-compose.yml" blog
# - name: Run migrations
#   command: docker --log-level ERROR exec $(docker ps -q -f name=blog_rails | head -n 1) rails db:migrate
